In [10]:
from numpy import array as ar
from numpy import fromfunction
T=fromfunction(lambda i,j: 60*(i+1)*(j+1),(2,3))
print(T)
U=fromfunction(lambda i,j: 5*(i+1)+2*(j+1),(3,4))
print(U)
C = T.dot(U)
print(C)
print(f'Al interpretar el elemento C[12]: podemos decir el costo de produccion total de 5640 dolares del mes 2 correspondiente a la bodega 1')

[[ 60. 120. 180.]
 [120. 240. 360.]]
[[ 7.  9. 11. 13.]
 [12. 14. 16. 18.]
 [17. 19. 21. 23.]]
[[ 4920.  5640.  6360.  7080.]
 [ 9840. 11280. 12720. 14160.]]
Al interpretar el elemento C[12]: podemos decir el costo de produccion total de 5640 dolares del mes 2 correspondiente a la bodega 1
