In [7]:
from numpy import array as ar

A = ar([[1.5,1.9],
        [0.9,1.2],
        [1.8,1.4]])

B = ar([[461,757,584,512],
        [512,690,506,471]])

C = A.dot(B)

print(C)

F=B.T
print(F)
J = F.dot(B) 
print(J)

[[1664.3 2446.5 1837.4 1662.9]
 [1029.3 1509.3 1132.8 1026. ]
 [1546.6 2328.6 1759.6 1581. ]]
[[461 512]
 [757 690]
 [584 506]
 [512 471]]
[[ 474665  702257  528296  477184]
 [ 702257 1049149  791228  712574]
 [ 528296  791228  597092  537334]
 [ 477184  712574  537334  483985]]
